### PR TITLE
Js TDD practice

### PR DESCRIPTION
**Pull request by kirokoNjenga**
- Practice JavaScript TDD using Jest.

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
# Changes Required

## Hi team :wave: 

Your tests are passing :100: 

However, there are few details we need to check off.

[**Required**] 

- [x] In your README, update this sentence `To install jest run npm install.` You can't install jest with npm install, rather it should install all the **`dev dependencies`** needed to run the project.

- [x] Your pull request comment, should have the list of the features you have implemented in the project. For example in this pull request, you should provide the list of the functions you have tested, and also any additional detail you would like the **`TSE`** reviewing your code to be aware of. Use this link as a reference . . . ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)))

[**Observations**] 

- [x] This project should be collaboratively worked on, however, @Samkiroko worked on it alone. Please let student success be aware of this, especially if it is due to challenges with your coding partner.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Comment by kirokoNjenga** [comment]
- for me, the above review was not worth it.
- I believe the goal the exercise is to practice testing which I have achieved, 
- test  done:   
1. array analysis
2.caesar cipher
3.capitalize
4.reverse string

**Comment by kirokoNjenga** [comment]
- Am working alone, I was not paired

**Review by uche-inyama — APPROVED** [review]
## Approved

This project is approved.

#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Pull request merged**
